name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev

      - name: Build
        run: |
          cmake -S . -B build
          cmake --build build -j$(nproc)

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
